create table countries (
    id bigint generated by default as identity primary key,
    name varchar(100) not null unique,
    iso_code_alpha_2 varchar(2) not null unique,
    currency_id smallint not null
);