create table users (
    id bigint generated by default as identity primary key,
    uuid uuid not null unique,
    phone_country_code varchar(5) not null,
    phone_number varchar(20) not null,
    password_hash varchar(255) not null,
    country_id bigint not null,
    is_verified boolean not null default false,
    created_at timestamptz not null default now(),

    constraint uq_users_phone unique (phone_country_code, phone_number),
    constraint fk_users_country foreign key (country_id) references countries(id)
);

create index idx_users_country_id on users(country_id);