create table roles (
    id int generated by default as identity primary key,
    name varchar(50) unique not null
)

create table users (
    id bigint generated by default as identity primary key,
    email varchar(255) unique not null,
    password_hash varchar(255) not null,
    role_id int not null,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now(),

    constraint fk_users_role foreign key (role_id) references roles(id)
)